# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Authentication-Basic-Remote
version:      0.02
version_from: lib/Catalyst/Plugin/Authentication/Basic/Remote.pm
installdirs:  site
requires:
    Catalyst:                      5.30
    LWP::UserAgent:                0
    MIME::Base64:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
