abstract: (DEPRECATED) Basic authentication via remote host.
author: Daisuke Murase, <typester@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Plugin-Authentication-Basic-Remote
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.30
  LWP::UserAgent: 0
  MIME::Base64: 0
version: 0.03
